FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
COPY tsconfig.json ./
COPY prisma ./prisma

RUN npm install
RUN npx prisma generate


# Copy all source files
COPY . .

# Install ts-node-dev globally (optional if already in package.json)
# RUN npm install -g ts-node-dev

EXPOSE 3001

CMD ["npm", "run", "dev"]
